"use client";

import { useActionState } from "react";
import { LockKeyhole, ShoppingBag } from "lucide-react";
import { login } from "./actions";

export default function LoginPage() {
  const [state, action, pending] = useActionState(login, { error: "" });
  return <main className="grid min-h-screen place-items-center bg-zinc-50 px-4 py-10"><section className="w-full max-w-md rounded-2xl border bg-white p-6 shadow-sm sm:p-8"><div className="mb-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-zinc-950 text-white shadow-sm"><ShoppingBag size={27} strokeWidth={2.2} /></div><p className="mt-5 text-sm font-medium text-zinc-500">Espace professionnel</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Babs Shop</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-zinc-600">Connectez-vous pour gérer votre catalogue, vos stocks et vos commandes en toute sécurité.</p></div><form action={action} className="space-y-4"><label className="block text-sm font-medium">Adresse e-mail<input required name="email" type="email" autoComplete="email" placeholder="vous@exemple.com" className="mt-1.5 w-full rounded-lg border px-3 py-3 outline-none transition focus:border-zinc-950 focus:ring-2 focus:ring-zinc-200" /></label><label className="block text-sm font-medium">Mot de passe<input required name="password" type="password" autoComplete="current-password" placeholder="Votre mot de passe" className="mt-1.5 w-full rounded-lg border px-3 py-3 outline-none transition focus:border-zinc-950 focus:ring-2 focus:ring-zinc-200" /></label>{state.error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}<button disabled={pending} className="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-zinc-950 p-3 font-semibold text-white transition hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-60"><LockKeyhole size={18} />{pending ? "Connexion…" : "Se connecter"}</button></form></section></main>;
}
