import Image from "next/image";
import Link from "next/link";
import { Plus, Pencil } from "lucide-react";
import { db } from "@/lib/db";
import { DeleteProductButton } from "@/components/admin/delete-product-button";

export const dynamic = "force-dynamic";
export default async function ProductsPage() {
  const products = await db.query.products.findMany({ with: { images: true, variants: true }, orderBy: (products, { desc }) => [desc(products.updatedAt)] });
  return <main className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8"><div className="mb-7 flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-zinc-500">Administration</p><h1 className="text-2xl font-bold sm:text-3xl">Produits</h1></div><Link href="/admin/products/new" className="inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-4 py-2.5 font-medium text-white"><Plus size={18} />Ajouter</Link></div>{products.length === 0 ? <div className="rounded-xl border border-dashed p-10 text-center"><h2 className="text-lg font-semibold">Aucun produit pour le moment</h2><p className="mt-2 text-sm text-zinc-500">Crée ton premier article, ajoute ses images et renseigne son stock.</p><Link href="/admin/products/new" className="mt-5 inline-flex rounded-lg bg-zinc-950 px-4 py-2.5 text-sm font-medium text-white">Créer un produit</Link></div> : <div className="overflow-hidden rounded-xl border"><div className="grid grid-cols-[72px_minmax(0,1fr)_auto] gap-3 border-b bg-zinc-50 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-zinc-500 sm:grid-cols-[80px_minmax(0,1fr)_130px_110px_180px]"><span>Image</span><span>Produit</span><span className="hidden sm:block">Prix</span><span className="hidden sm:block">Stock</span><span>Actions</span></div>{products.map((product) => { const stock = product.variants.reduce((sum, variant) => sum + variant.stock, 0); return <div key={product.id} className="grid grid-cols-[72px_minmax(0,1fr)_auto] items-center gap-3 border-b px-4 py-3 last:border-0 sm:grid-cols-[80px_minmax(0,1fr)_130px_110px_180px]"><div className="relative h-14 w-14 overflow-hidden rounded-md bg-zinc-100">{product.images[0] && <Image src={product.images[0].url} alt={product.name} fill sizes="56px" className="object-cover" />}</div><div className="min-w-0"><p className="truncate font-medium">{product.name}</p><p className="truncate text-sm text-zinc-500">/{product.slug} <span className="sm:hidden">· ₣{Number(product.price).toLocaleString("fr-FR")}</span></p></div><p className="hidden sm:block">₣{Number(product.price).toLocaleString("fr-FR")}</p><p className="hidden sm:block"><span className={product.variants.length && stock === 0 ? "font-medium text-red-700" : ""}>{product.variants.length ? stock : "—"}</span></p><div className="flex flex-wrap items-center gap-1"><Link href={`/admin/products/${product.id}/edit`} className="inline-flex items-center gap-1.5 rounded-md p-2 text-sm font-medium hover:bg-zinc-100"><Pencil size={17} />Modifier</Link><DeleteProductButton id={product.id} /></div></div>; })}</div>}</main>;
}
